# Generated by Django 3.1 on 2020-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='time',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
        ),
    ]
