# Generated by Django 3.1 on 2020-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_training_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.DateTimeField(default='2020-10-01 09:51:56'),
        ),
    ]
