# Generated by Django 3.1 on 2020-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20201001_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.DateTimeField(default='2020-10-01 10:25'),
        ),
    ]
