# Generated by Django 3.1 on 2020-10-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20201001_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.DateTimeField(default='2020-10-01 12:47'),
        ),
    ]
