# Generated by Django 3.1 on 2020-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_auto_20201001_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='time',
        ),
        migrations.AddField(
            model_name='training',
            name='dateTime',
            field=models.DateTimeField(default='2020-10-02 18:10'),
        ),
    ]
