# Generated by Django 3.1 on 2020-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_auto_20201002_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateTimeField(default='2020-10-02 18:28'),
        ),
        migrations.AddField(
            model_name='training',
            name='time',
            field=models.DateTimeField(default='2020-10-02 18:28'),
        ),
        migrations.AlterField(
            model_name='training',
            name='dateTime',
            field=models.DateTimeField(default='2020-10-02 18:28'),
        ),
    ]
