# Generated by Django 3.1 on 2020-10-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_auto_20201002_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='date',
        ),
        migrations.RemoveField(
            model_name='training',
            name='dateTime',
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.DateTimeField(default='2020-10-03 19:12'),
        ),
    ]
