# Generated by Django 3.1 on 2020-10-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_auto_20201003_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='time',
        ),
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateTimeField(default='2020-10-04 11:32'),
        ),
    ]
