# Generated by Django 3.1 on 2020-10-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_auto_20201006_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='adress',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(default='2020-10-08 09:32'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
