# Generated by Django 3.1 on 2020-10-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0017_auto_20201013_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(default='2020-10-13 17:40'),
        ),
    ]
