# Generated by Django 3.1 on 2020-10-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_auto_20201013_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='maxParticipants',
            field=models.PositiveSmallIntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(default='2020-10-14 15:37'),
        ),
    ]
