# Generated by Django 3.1 on 2020-10-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0019_auto_20201014_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='organizedTrainings',
            field=models.ManyToManyField(blank=True, related_name='organizer', to='trainings.Training'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(default='2020-10-15 13:32'),
        ),
        migrations.AlterField(
            model_name='training',
            name='maxParticipants',
            field=models.PositiveSmallIntegerField(blank=True, default=10),
        ),
    ]
