# Generated by Django 3.1 on 2020-10-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0020_auto_20201015_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(default='2020-10-15 14:24'),
        ),
    ]
