# Generated by Django 3.1 on 2020-10-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0021_auto_20201015_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(default='2020-10-20 09:00'),
        ),
    ]
