# Generated by Django 3.1 on 2020-10-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0022_auto_20201020_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(default='2020-10-20 09:01'),
        ),
    ]
